version: '3'
services:
  libretranslate:
    image: libretranslate/libretranslate
    restart: always
    ports:
      - "5000:5000"
    environment:
      - LT_UPDATE_MODELS=true
      - LT_LOAD_ONLY=en,ar
    volumes:
      - libretranslate-data:/app/libretranslate/db

volumes:
  libretranslate-data: 