services:
  - type: web
    name: octopus-ai-mvp
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    autoDeploy: true
    envVars:
      - key: PYTHONUNBUFFERED
        value: "true"
      - key: STREAMLIT_SERVER_ENABLE_XSRF_PROTECTION 
        value: "false"
      - key: STREAMLIT_SERVER_HEADLESS
        value: "true"
      - key: STREAMLIT_SERVER_ADDRESS
        value: "0.0.0.0" 