services:
  - type: web
    name: chatbot-mvp
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    autoDeploy: true
    envVars:
      - key: PYTHONUNBUFFERED
        value: "true"
      - key: STREAMLIT_SERVER_ENABLE_XSRF_PROTECTION 
        value: "false"
      - key: STREAMLIT_SERVER_HEADLESS
        value: "true"
      - key: STREAMLIT_SERVER_ADDRESS
        value: "0.0.0.0"
      - key: LIBRETRANSLATE_HOST
        value: "localhost"
      - key: LIBRETRANSLATE_PORT
        value: "5000" 