name: Sync to Hugging Face Space

on:
  push:
    branches: [main]

jobs:
  sync-to-hf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Push to Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git remote add hf https://malakstar786:${HF_TOKEN}@huggingface.co/spaces/Merpec/octopus-multilingual-mvp
          git push hf main --force
